### ISSUE TITLE
Address bar only showing first result

### ISSUE THREAD

**Issue by OfficialEsco** [LuckyLuuk12/firefox-vertical-tabs#1]
This line causes the address bar to not work as expected (On Linux at least)
https://github.com/LuckyLuuk12/firefox-vertical-tabs/blob/b92ea0ff52d3a10e3d73b3c6c3f36cb2ecdd907e/userChrome.css#L25C1-L25C17
![image](https://github.com/user-attachments/assets/e0d4fc76-fcd0-44ab-a63a-8429678e3d8d)

**Comment by LuckyLuuk12** [comment]
Thank you for spotting that mistake, I just fixed it (hopefully as well on Linux) 
Just removing that (useless) line seemed to be enough to fix it.. :)
