### ISSUE TITLE
v132.0.1 styling issues

### ISSUE THREAD

**Issue by LuckyLuuk12** [LuckyLuuk12/firefox-vertical-tabs#7]
I've noticed that some things are not very similar to the v130 version.

- [x] Sidebar is more wide
- [x] On hover of tabs has incorrectly sized lighter effect
- [x] there appears to be more padding/margin around the tabs
- [x] Icons appear to be a bit larger but cannot confirm?
- [ ] v130 was broken on (old) Ubuntu distro so I assume it will be on v132.0.1 as well
- [x] no "new tab" text next to "+" icon for new tabs

**Comment by OfficialEsco** [comment]
in what way was it broken on Ubuntu?
Could it be that this was disabled in Customize Toolbar?
![image](https://github.com/user-attachments/assets/0a8a9ee2-dd86-4862-a201-bce450e0f2c6)

the + for new Tab also appears to move when hovering over the sidebar, i also see Firefox added a new tab button which works the same way as Sideberry (with containers)
![image](https://github.com/user-attachments/assets/f72cb83f-d792-422b-bc91-a56d750a6934)
Would it be possible to get that as a new tab button? (you can currently Long Press on the current one for the same container function)

**Comment by OfficialEsco** [comment]
didnt see your test branch, seems like you fixed the new tab moving, the container visibility is a bit weird
![image](https://github.com/user-attachments/assets/ab366422-bfe1-40ee-ac1b-bcce294f0115)

**Comment by LuckyLuuk12** [comment]
What OS are you testing on? I currently only have access to a Windows 10 device and my Dual Boot Linux (Ubuntu) is pretty outdated and I cannot upgrade it because my laptop has no space left... So sadly enough I cannot test for any other OS than Windows 10... 

On Ubuntu my current code was basically "removing" the whole sidebar and browser it kept on "glitching" at the top of my screen as if I was using float and position absolute on all containers... I don't know if I have done already but I'll push my latest code and perhaps I can them merge to main and let you do a Linux/MacOS version? I also don't mind if you want to collab on this repo?

**Comment by OfficialEsco** [comment]
I'm only testing on Linux - Arch, but the only difference should be how the Title bar works.  
I'll boot up my Windows VM in an hour to see if it's any different, I'm just amazed this is the only proper native vertical tab, these repos keep dying so just trying to keep it alive :)

**Comment by OfficialEsco** [comment]
Not an hour, but can confirm its the same on Windows, do you use containers at all?

**Comment by LuckyLuuk12** [comment]
![image](https://github.com/user-attachments/assets/be5c3aa8-2310-4e20-82f8-a11e5c6ba330)
I just use normal tabs, no containers or whatsoever as you can see... though if you experience issues with that I could look at it in a few days? (just have to find out what you use/ how to use those "containers")

**Comment by OfficialEsco** [comment]
I think its built in, unless its on Librewolf, Long press on New Tab, its not too much of a problem tho =)

**Comment by OfficialEsco** [comment]
Found the line making the container indicator overlap
https://github.com/LuckyLuuk12/firefox-vertical-tabs/blob/5da485d1957e76204aa9312df4dab7ae11429242/userChrome.css#L50
i've enabled the border for troubleshooting, but by default the container tab is all the way to the left
![image](https://github.com/user-attachments/assets/8e48ddf3-1e92-4373-8513-c95967a5728d)

**Comment by LuckyLuuk12** [comment]
I've just read a bit into what those containers are but visually they only add a colored line, am I right??  So the fix would just be to move that line to the left or something such that it is aligned with the tab border? (In your screenshots the green line right?)

**Comment by OfficialEsco** [comment]
Yup! It adds a line matching the profile color

**Comment by LuckyLuuk12** [comment]
I'll try to fix it in the next 30 minutes, if it's not fixed by then I'll try to fix it later today 👍🏻 
any other weird styling issues that you have spotted so far?

**Comment by OfficialEsco** [comment]
Nothing to stress over =)
Nah looks good, there is one functionality which kinda annoys me, i wish right clicking a tab would leave the sidebar open, i cannot remember if some other vertical tab css made this work, but since other projects got this annoyance its pretty much "normal" behavior

**Comment by LuckyLuuk12** [comment]
I just read that containers is actually an extension. So I would either have to install it temporarily to fix this or maybe you can try to fix it yourself. About that other behaviour you mention. You want it to stay open when right clicked if I understand correctly? It sounds doable but idk if it is that doable with only css...

**Comment by LuckyLuuk12** [comment]
I've also noticed that there is a 132.0.3 version out already but as far as I know the vertical nav bar did not change (or at least not enough to annoy the visual appearance with the css of this branch)

**Comment by OfficialEsco** [comment]
Its very confusing, because its both, if you install a extension it overtakes the inbuilt one which is very weak. Mozilla then got their own extension which makes it smarter and sync https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
![image](https://github.com/user-attachments/assets/3959ced3-f644-49cc-bc2f-b35d1e00de9d)
I'm confused how containers worked on vanilla Librewolf without signing in tho, my VM dosn't work on this PC so i cannot test vanilla Firefox before i get home.


And yes i agree its probably not doable with only css, so its probably a bigger "mod" i downloaded which is why its not in most vertical tab css's

**Comment by LuckyLuuk12** [comment]
I managed to fix the containers pushing it now

**Comment by OfficialEsco** [comment]
Ohhhh you did end up using .tab-label-container, i was looking at it but didn't manage to make it work myself, beautiful
